### PR TITLE
IJulia notebooks on using JuMP for optimization

### PR DESCRIPTION
**Pull request by Shuvomoy**
These are the notebooks I prepared for a tutorial on using JuMP, given at UTORG, University of Toronto.

### CODE REVIEW

**Comment by mlubin** [comment]
We need a little bot to post nbviewer links to PRs :)
http://nbviewer.ipython.org/github/Shuvomoy/juliaopt-notebooks/tree/master/notebooks/

**Comment by mlubin** [comment]
Thanks for contributing these! We've more than doubled the available content.
A few comments:
- We haven't really settled on naming conventions, but there will certainly be multiple notebooks on column generation, benders decomposition, and "getting started" in the future. I would suggest prefixing the notebook names with `UTORG-` or `Shuvo-` or `Shuvomoy-` for now. I'm hoping to figure out a reasonable way to make the notebooks searchable #3.
- In the benders decomposition and column generation notebooks, could you replace the use of `@defConstrRef` with the three-argument version of `@addConstraint`? E.g.

```
@defConstrRef consRef[1:cardinalityM] # References for the constraints
for (i in M)
    consRef[i] = @addConstraint(cutstockMain, sum{A[i,j]*x[j], j in Jprime}==b[i])
end
```

becomes

```
@addConstraint(cutstockMain, consRef[i=1:cardinalityM], sum{A[i,j]*x[j], j in Jprime}==b[i])
```

We prefer this form and only recommend `@defConstrRef` for cases where the more compact syntax is difficult to apply.
- In the "getting started" notebook, you may want to add a note that to use the CPLEX, Gurobi, and Mosek packages, you first need to set up the software and appropriate licences.
- The use of `\preceq` instead of `\leq` for element-wise inequality seems a bit unusual to me, although I'm aware that some authors use it. Could you add a note of its meaning?

**Comment by Shuvomoy** [comment]
Hi Miles,

Thanks. I will make the changes that you suggested and upload them soon.

Best Regards,
Shuvo

**Comment by Shuvomoy** [comment]
Hi Miles,

Made the changes suggested by you. Here is the nbviewer link:

http://nbviewer.ipython.org/github/Shuvomoy/juliaopt-notebooks/tree/master/notebooks/

Please let me know if I need to make any other changes.

Regards,
Shuvo

**Comment by mlubin** [comment]
LGTM. @IainNZ, @joehuchette, any comments?
I will also double check that the notebooks run locally before merging.

**Comment by IainNZ** [comment]
They're very impressive work, I like them a lot. LGTM.

**Comment by mlubin** [comment]
No issues with running the notebooks. Thanks for the contribution!

**Comment by Shuvomoy** [comment]
Thanks for merging the pull request!

**Pull request merged**
