### PR TITLE
Jdg/deprecationfixes

### PR DESCRIPTION
**Pull request by joaquimg**
Updating the Shuvomoy notebooks for the new JuMP syntax

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks!
I'm working on some changes to parsing the generator syntax that will break some corner cases (``for i in 1:N, j in 1:i`` becomes ``for i in 1:N for j in 1:i`` to be consistent with Julia), but everything seems to be fine here.
CC @Shuvomoy

**Comment by joaquimg** [comment]
But the single worded and comma separated is already consistent, isnt it?

Actually I prefer the single worded for with comma separator, I think its cleaner, consistent with 0.5 at least and makes a lot of sense for double index sums.

Just a suggestion...

Joaquim

**Comment by mlubin** [comment]
@joaquimg, ``sum(i for i in 1:3, j in 1:i)`` is what we currently use within macros, but this isn't consistent with Julia.

**Comment by mlubin** [comment]
Ref https://github.com/JuliaOpt/JuMP.jl/pull/896

**Pull request merged**
