### PR TITLE
Update Rocket notebook for release JuMP 0.19

### PR DESCRIPTION
**Pull request by barpit20**
I removed the line about the MathOptInterface version this notebook is based on since we are not directly using MOI anywhere. I hope that's ok.

@blegat @chriscoey @joaquimg

### CODE REVIEW

**Comment by matbesancon** [comment]
bump here?

**Comment by odow** [comment]
These have been superseded by https://github.com/JuliaOpt/JuMPTutorials.jl

**Comment by matbesancon** [comment]
thanks, should this repo be archived and the replacement indicated in the README?

**Comment by cdeil** [comment]
@barpit20  - Close this old PR?

It has landed here, no?
https://nbviewer.jupyter.org/github/JuliaOpt/JuMPTutorials.jl/blob/master/notebook/modelling/rocket_control.ipynb

**Pull request closed without merging**
