### PR TITLE
matrix completion examples

### PR DESCRIPTION
**Pull request by ahwillia**

### CODE REVIEW

**Comment by IainNZ** [comment]
Hi @ahwillia, thanks for the PR. Would you be willing to put a license on these notebooks? We've been using the same CC license consistently: https://github.com/JuliaOpt/juliaopt-notebooks/blob/master/notebooks/JuMP-Rocket.ipynb

**Comment by ahwillia** [comment]
@IainNZ thanks! How does it look now?

https://github.com/ahwillia/juliaopt-notebooks/blob/master/notebooks/Matrix%20Completion%20with%20Binary%20Data.ipynb

https://github.com/ahwillia/juliaopt-notebooks/blob/master/notebooks/Matrix%20Completion.ipynb

**Comment by mlubin** [comment]
It looks like there are some checkpoint files included in the PR, could you remove these?

**Comment by mlubin** [comment]
Also, is `Matrix Completion.ipynb` meant to be a complete notebook? It's not really clear.

**Comment by ahwillia** [comment]
@mlubin -- thanks, I've added some background information now. I just had this lying around and should have cleaned it up a bit before sending it out. Happy to hear more feedback/criticisms.

**Comment by IainNZ** [comment]
I think it looks great to me. Lets merge them in, and can touch anything else up later.

**Pull request merged**
